let jobs = [
    { id: 1, 
        company: "Mobile First Crop", 
        position: "React Native Developer", 
        location: "Remote", 
        type: "Full-time", 
        salary: "$80,000 - $110,000", 
        description: "Develop high-performance mobile application using React Native for iOS and Android platforms.", status: "all" },
    { id: 2, 
        company: "WebFlow Agency", 
        position: "Web Designer & Developer", 
        location: "San Francisco, CA", 
        type: "Part-time", 
        salary: "$50,000 - $60,000", 
        description: "Creating visually stunning and highly functional websites for a variety of clients using modern web design tools.", 
        status: "all" },
    { id: 3, 
        company: "DataViz Solutions", 
        position: "Data Visualization Specialist", 
        location: "New York, NY", 
        type: "Full-time", 
        salary: "$95,000 - $125,000", 
        description: "Transform complex data sets into compelling visual stories using D3.js, Tableau, and custom web tools.", 
        status: "all" },
    { id: 4, 
        company: "CloudFirst Inc", 
        position: "Backend Developer", 
        location: "Seattle, WA", 
        type: "Full-time", 
        salary: "$110,000 - $140,000", 
        description: "Design and maintain scalable server-side systems using Node.js and Python. Experience with AWS infrastructure is required.", 
        status: "all" },
    { id: 5, 
        company: "Innovation Labs", 
        position: "UI/UX Designer", 
        location: "Austin, TX", 
        type: "Full-time", 
        salary: "$75,000 - $90,000", 
        description: "Create beautiful and intuitive user interfaces for our suite of products. Strong background in user-centered design is expected.", 
        status: "all" },
    { id: 6, 
        company: "MegaCorp Solutions", 
        position: "JavaScript Developer", 
        location: "Chicago, IL", 
        type: "Full-time", 
        salary: "$100,000 - $120,000", 
        description: "Build enterprise applications with JavaScript and reactive frameworks. We offer competitive compensation and professional development.", 
        status: "all" },
    { id: 7, 
        company: "StartupXYZ", 
        position: "Full Stack Engineer", 
        location: "Remote", 
        type: "Full-time", 
        salary: "$90,000 - $115,000", 
        description: "Join our fast-growing startup and work on our core platform. Experience with React and PostgreSQL is highly valued.", 
        status: "all" },
    { id: 8, 
        company: "TechHub Industries", 
        position: "Senior Frontend Developer", 
        location: "San Jose, CA", 
        type: "Full-time", 
        salary: "$130,000 - $155,000", 
        description: "Lead our frontend team to build scalable web applications using React and TypeScript. Focus on performance and accessibility.", 
        status: "all" }
];